import { createHash } from 'node:crypto';
import type { INestApplication } from '@nestjs/common';
import type { TestDatabase } from '@procesabpm/db/testing/database';
import { PDFDocument } from 'pdf-lib';
import { extractText, getDocumentProxy } from 'unpdf';
import { afterAll, beforeAll, describe, expect, inject, it } from 'vitest';
import { S3ObjectStorage } from '../../src/infrastructure/storage/s3-object-storage.js';
import { connectTestDatabase } from '../support/admin-api.js';
import { createTestApp } from '../support/create-test-app.js';
import { declare, putToStorage } from '../support/file-uploads.js';
import { useTestEnvironment } from '../support/test-environment.js';
import { type Member, publishFlow, publishVersion, type PublishedFlow, simpleFlow, TicketWorld, unique } from '../support/ticket-world.js';
import { MailWorker } from '../support/worker-mail.js';
import { expectStatus } from '../support/supertest-diagnostics.js';

useTestEnvironment();

const grant = (action: string) => ({ action, subject: 'Ticket' });
const user = (member: Member) => ({ participantType: 'USER', userId: member.userId });
const textOf = async (bytes: Uint8Array): Promise<string> => (await extractText(await getDocumentProxy(new Uint8Array(bytes)), { mergePages: true })).text;

const DESIGN = {
  version: 1,
  page: { size: 'A4', orientation: 'PORTRAIT', margins: { top: 54, right: 54, bottom: 54, left: 54 } },
  defaults: { fontSize: 10 },
  body: [
    { type: 'heading', text: 'Orden {{ticket.number}} – Acción', level: 1 },
    { type: 'text', text: 'Proveedor: {{field.PROVIDER}} · Valor {{field.AMOUNT|currency}}' },
    { type: 'allFields' },
  ],
} as const;

describe('documents: designer formats and uploaded templates, generated by the worker', () => {
  let db: TestDatabase;
  let app: INestApplication;
  let worker: MailWorker;
  let world: TicketWorld;
  let requester: Member;
  let assignee: Member;
  let stranger: Member;
  let flow: PublishedFlow;
  const storage = new S3ObjectStorage({ ...inject('storage'), forcePathStyle: true });

  const base = () => `/workflows/${flow.workflowId}`;
  const create = async (values: Record<string, unknown> = { PROVIDER: 'Ñandú S.A.', AMOUNT: 1500000 }) =>
    (await requester.client.post('/tickets', { subcategoryId: flow.subcategoryId, title: unique('Ticket'), values }).expect(201)).body as { id: string; openVisitId: string };
  const advance = (ticket: { id: string; openVisitId: string }) => assignee.client.post(`/tickets/${ticket.id}/transition`, { transitionId: flow.transition.Done!, visitId: ticket.openVisitId, values: {} }).expect(200);
  const documentsOf = async (ticketId: string) => (await requester.client.get(`/tickets/${ticketId}/documents`).expect(200)).body as Array<{ role: string; version: number; isCurrent: boolean; file: { id: string; name: string } }>;
  const rows = async (ticketId: string) =>
    (await db.platform.query<{ version: number; is_current: boolean; role: string; file_id: string; storage_key: string; size_bytes: string; sha256: string; origin: string; status: string; linked_at: Date | null; uploaded_by_id: string | null }>(
      `SELECT d.version, d.is_current, d.role, d.file_id, f.storage_key, f.size_bytes::text, f.sha256, f.origin, f.status, f.linked_at, f.uploaded_by_id FROM ticket_documents d JOIN stored_files f ON f.tenant_id = d.tenant_id AND f.id = d.file_id WHERE d.tenant_id = $1 AND d.ticket_id = $2 ORDER BY d.version`,
      [world.tenant.tenantId, ticketId],
    )).rows;
  const usedBytes = async (tenantId = world.tenant.tenantId) => BigInt((await db.platform.query<{ bytes_used: string }>('SELECT bytes_used::text FROM tenant_usage WHERE tenant_id = $1', [tenantId])).rows[0]?.bytes_used ?? '0');
  const download = async (storageKey: string) => storage.read(storageKey, 20 * 1024 * 1024);
  const newFormat = async (design: unknown = DESIGN, extra: Record<string, unknown> = {}) => (await world.admin.post(`${base()}/pdf-formats`, { name: unique('Formato'), design, ...extra }).expect(201)).body as { id: string };
  const bindFormat = async (formatId: string, moment: string | null) => (await world.admin.post(`${base()}/documents`, { formatId, moment }).expect(201)).body as { id: string };

  beforeAll(async () => {
    db = connectTestDatabase();
    ({ app } = await createTestApp());
    worker = await MailWorker.start();
    world = await TicketWorld.create(db, app);
    requester = await world.member([grant('create'), grant('read_created')]);
    assignee = await world.member([grant('read_assigned'), grant('transition'), grant('close')]);
    stranger = await world.member([grant('read_created')]);
    flow = await publishFlow(world.admin, {
      ...simpleFlow({ assignmentMode: 'USERS' }, { candidates: [user(assignee)] }),
      fields: [
        { step: 'start', code: 'PROVIDER', type: 'TEXT', capture: 'CREATION' },
        { step: 'start', code: 'AMOUNT', type: 'CURRENCY', capture: 'CREATION' },
      ],
    });
  });

  afterAll(async () => {
    await worker.close();
    await app.close();
    await db.close();
  });

  describe('a designer format produces a document when the ticket is created', () => {
    let ticketId: string;
    let bindingId: string;

    beforeAll(async () => {
      bindingId = (await bindFormat((await newFormat()).id, 'CREATION')).id;
      const before = await usedBytes();
      ticketId = (await create()).id;
      await worker.deliver();
      expect(await usedBytes()).toBeGreaterThan(before);
    });

    afterAll(async () => {
      await world.admin.patch(`${base()}/documents/${bindingId}`, { isActive: false }).expect(200);
    });

    it('stores one current MAIN document as a confirmed, linked SYSTEM file with no uploader', async () => {
      const [document, ...rest] = await rows(ticketId);
      expect(rest).toEqual([]);
      expect(document).toMatchObject({ version: 1, is_current: true, role: 'MAIN_DOCUMENT', origin: 'SYSTEM', status: 'CONFIRMED', uploaded_by_id: null });
      expect(document!.linked_at).not.toBeNull();
    });

    it('draws accents, ñ and the ticket data, in a valid PDF', async () => {
      const [document] = await rows(ticketId);
      const bytes = await download(document!.storage_key);
      expect(createHash('sha256').update(bytes).digest('hex')).toBe(document!.sha256);
      expect(String(bytes.length)).toBe(document!.size_bytes);
      const text = await textOf(bytes);
      expect(text).toContain('Acción');
      expect(text).toContain('Ñandú S.A.');
      expect(text).toContain('1.500.000');
    });

    it('the person who can read the ticket lists and downloads it; a stranger cannot', async () => {
      const [document] = await documentsOf(ticketId);
      expect(document).toMatchObject({ role: 'MAIN_DOCUMENT', version: 1, isCurrent: true });
      const url = (await requester.client.get(`/tickets/${ticketId}/files/${document!.file.id}/download-url`).expect(200)).body.url as string;
      const response = await fetch(url);
      expectStatus(response, 200);
      expect(new Uint8Array(await response.arrayBuffer()).slice(0, 5)).toEqual(new Uint8Array([0x25, 0x50, 0x44, 0x46, 0x2d]));
      await stranger.client.get(`/tickets/${ticketId}/documents`).expect(404);
      await stranger.client.get(`/tickets/${ticketId}/files/${document!.file.id}/download-url`).expect(404);

      // The access is in the trail (one row for the requester, none for the refused stranger).
      const trail = await db.owner.query<{ actor_id: string; entity_id: string; after: { ticketId: string } }>(
        `SELECT actor_id, entity_id, after FROM audit_logs WHERE tenant_id = $1 AND action = 'file.download_url_issued' AND entity_id = $2`,
        [world.tenant.tenantId, document!.file.id],
      );
      expect(trail.rows).toEqual([expect.objectContaining({ actor_id: requester.userId, after: expect.objectContaining({ ticketId }) })]);
    });

    it('delivering again changes nothing: one document, the usage counted once', async () => {
      const used = await usedBytes();
      await worker.deliver();
      expect(await rows(ticketId)).toHaveLength(1);
      expect(await usedBytes()).toBe(used);
    });

    it('an event that is processed a second time reuses the object and records nothing new', async () => {
      const used = await usedBytes();
      await db.platform.query(`UPDATE outbox_events SET status = 'PENDING', attempts = 0, processed_at = NULL, available_at = now() WHERE tenant_id = $1 AND type = 'document.generate' AND payload->>'ticketId' = $2`, [world.tenant.tenantId, ticketId]);
      await worker.deliver();
      expect(await rows(ticketId)).toHaveLength(1);
      expect(await usedBytes()).toBe(used);
    });
  });

  describe('versions: each step draws a new one and never touches the old ones', () => {
    it('creation draws v1 and the last step draws v2, as the only current row, with the old object unchanged', async () => {
      const onCreation = await bindFormat((await newFormat({ ...DESIGN, body: [{ type: 'text', text: 'Al crear: {{ticket.status}}' }] })).id, 'CREATION');
      const onSteps = await bindFormat((await newFormat({ ...DESIGN, body: [{ type: 'text', text: 'Al avanzar: {{ticket.status}}' }] })).id, 'EACH_STEP');
      const ticket = await create();
      await worker.deliver();
      const [first] = await rows(ticket.id);
      expect(first).toMatchObject({ version: 1, is_current: true });
      const firstBytes = await download(first!.storage_key);
      expect(await textOf(firstBytes)).toContain('Al crear: Abierto');

      await advance(ticket);
      await worker.deliver();
      const all = await rows(ticket.id);
      expect(all.map((row) => row.version)).toEqual([1, 2]);
      expect(all.map((row) => row.is_current)).toEqual([false, true]);
      expect(await textOf(await download(all[1]!.storage_key))).toContain('Al avanzar: Cerrado');
      expect(Buffer.from(await download(first!.storage_key)).equals(Buffer.from(firstBytes))).toBe(true);
      expect(new Set(all.map((row) => row.storage_key)).size).toBe(2);
      for (const binding of [onCreation, onSteps]) await world.admin.patch(`${base()}/documents/${binding.id}`, { isActive: false }).expect(200);
    });
  });

  describe('signatures', () => {
    it('prints who moved the ticket on from the step, and when', async () => {
      const design = { ...DESIGN, body: [{ type: 'signatures', perRow: 2, height: 50, slots: [{ stepName: 'task', signerType: 'USER' }, { stepName: 'task', signerType: 'CREATOR', signerLabel: 'Solicitante' }] }] };
      const binding = await bindFormat((await newFormat(design)).id, 'CLOSING');
      const ticket = await create();
      await advance(ticket);
      await worker.deliver();
      const [document] = (await rows(ticket.id)).filter((row) => row.is_current);
      const text = await textOf(await download(document!.storage_key));
      expect(text).toContain('Firmado por');
      expect(text).toContain('Pendiente: Solicitante');
      await world.admin.patch(`${base()}/documents/${binding.id}`, { isActive: false }).expect(200);
    });
  });

  describe('an uploaded PDF template is filled by coordinates and by AcroForm field names', () => {
    it('registers it, maps fields, previews it and fills it for a ticket', async () => {
      const source = await PDFDocument.create();
      const page = source.addPage([400, 400]);
      const field = source.getForm().createTextField('proveedor');
      field.addToPage(page, { x: 50, y: 300, width: 200, height: 20 });
      const file = Buffer.from(await source.save());

      const slot = (await world.admin.post('/pdf-templates/uploads', { files: [declare({ name: 'plantilla.pdf', content: file })] }).expect(201)).body.uploads[0] as { fileId: string; url: string; method: string; headers: Record<string, string> };
      expect((await putToStorage(slot, file)).ok).toBe(true);
      await world.admin.post(`/pdf-templates/uploads/${slot.fileId}/confirm`).expect(200);

      const template = (await world.admin.post(`${base()}/pdf-templates`, { fileId: slot.fileId, name: unique('Plantilla') }).expect(201)).body as { id: string; hasAcroform: boolean; acroformFields: Array<{ name: string }>; pageCount: number };
      expect(template).toMatchObject({ hasAcroform: true, pageCount: 1, acroformFields: [{ name: 'proveedor', type: 'TEXT' }] });
      await world.admin.post(`${base()}/pdf-templates`, { fileId: slot.fileId, name: unique('Otra') }).expect(422);

      await world.admin
        .put(`${base()}/pdf-templates/${template.id}/mapping`, {
          fields: [
            { mode: 'ACROFORM', acroformName: 'proveedor', fieldCode: 'PROVIDER' },
            { mode: 'COORDINATES', page: 1, x: 60, y: 200, fontSize: 12, expression: 'Orden {{ticket.number}} de {{field.PROVIDER|upper}}' },
          ],
          signatures: [],
        })
        .expect(200);
      await world.admin.put(`${base()}/pdf-templates/${template.id}/mapping`, { fields: [{ mode: 'ACROFORM', acroformName: 'no_existe', fieldCode: 'PROVIDER' }], signatures: [] }).expect(422);
      await world.admin.put(`${base()}/pdf-templates/${template.id}/mapping`, { fields: [{ mode: 'COORDINATES', page: 1, x: 10, y: 10, fieldCode: 'NOPE' }], signatures: [] }).expect(422);

      const preview = await world.admin.post(`${base()}/pdf-templates/${template.id}/preview`, { values: { PROVIDER: 'Prueba Ñ' } }).expect(200);
      expect(preview.headers['content-type']).toContain('application/pdf');
      expect(preview.headers['cache-control']).toBe('no-store');
      expect(await textOf(preview.body as Uint8Array)).toContain('PRUEBA Ñ');

      const binding = (await world.admin.post(`${base()}/documents`, { templateId: template.id, moment: 'CLOSING' }).expect(201)).body as { id: string; kind: string };
      expect(binding.kind).toBe('TEMPLATE');
      const ticket = await create({ PROVIDER: 'Acme', AMOUNT: 10 });
      await worker.deliver();
      expect(await rows(ticket.id)).toEqual([]);
      await advance(ticket);
      await worker.deliver();
      const [document] = (await rows(ticket.id)).filter((row) => row.is_current);
      const filled = await PDFDocument.load(await download(document!.storage_key));
      expect(filled.getForm().getFields()).toHaveLength(0);
      const text = await textOf(await download(document!.storage_key));
      expect(text).toContain('Acme');
      expect(text).toContain('de ACME');

      await world.admin.delete(`${base()}/pdf-templates/${template.id}`).expect(409);
      await world.admin.delete(`${base()}/documents/${binding.id}`).expect(204);
      await world.admin.delete(`${base()}/pdf-templates/${template.id}`).expect(204);
    });
  });

  describe('a DOCUMENT block', () => {
    const emptyWorkflow = async () => {
      const category = (await world.admin.post('/categories', { name: unique('Cat') }).expect(201)).body.id as string;
      const subcategoryId = (await world.admin.post('/subcategories', { categoryId: category, name: unique('Sub') }).expect(201)).body.id as string;
      const workflow = (await world.admin.post('/workflows', { subcategoryId, name: unique('Flow') }).expect(201)).body;
      return { subcategoryId, workflowId: workflow.id as string, versionId: workflow.versions[0].id as string };
    };
    const spec = (config: Record<string, unknown>) => ({
      steps: [{ key: 'start', type: 'START' as const }, { key: 'doc', type: 'DOCUMENT' as const, extra: { config } }, { key: 'end', type: 'END' as const }],
      transitions: [{ from: 'start', to: 'doc', type: 'DEFAULT' as const }, { from: 'doc', to: 'end', type: 'DEFAULT' as const }],
    });

    it('draws a STEP document that remembers its step, and a draft naming a missing field cannot be published', async () => {
      const own = await emptyWorkflow();
      const ownBase = `/workflows/${own.workflowId}`;
      const format = (await world.admin.post(`${ownBase}/pdf-formats`, { name: 'f', design: { ...DESIGN, body: [{ type: 'text', text: 'Acta del paso' }] } }).expect(201)).body as { id: string };
      const binding = (await world.admin.post(`${ownBase}/documents`, { formatId: format.id }).expect(201)).body as { id: string };
      const flowSteps = await publishVersion(world.admin, own.workflowId, own.versionId, spec({ workflowDocumentId: binding.id, role: 'STEP_DOCUMENT' }));
      const ticket = (await requester.client.post('/tickets', { subcategoryId: own.subcategoryId, title: 't', values: {} }).expect(201)).body as { id: string };
      await worker.deliver();
      const [document] = await rows(ticket.id);
      expect(document).toMatchObject({ role: 'STEP_DOCUMENT', version: 1, is_current: true });
      const stored = await db.platform.query<{ step_id: string }>('SELECT step_id FROM ticket_documents WHERE tenant_id = $1 AND ticket_id = $2', [world.tenant.tenantId, ticket.id]);
      expect(stored.rows[0]!.step_id).toBe(flowSteps.step.doc);
      expect(await textOf(await download(document!.storage_key))).toContain('Acta del paso');
    });

    it('publishing is refused when a DOCUMENT block names a document that does not exist', async () => {
      const own = await emptyWorkflow();
      await expect(publishVersion(world.admin, own.workflowId, own.versionId, spec({ workflowDocumentId: '0199a000-0000-7000-8000-0000000000aa', role: 'MAIN_DOCUMENT' }))).rejects.toThrow(/BLOCK_REFERENCE_UNKNOWN|DOCUMENT_SOURCE_NOT_FOUND/);
    });

    it('publishing is refused (422) while a document the version produces names a field that is not there', async () => {
      const own = await emptyWorkflow();
      const ownBase = `/workflows/${own.workflowId}`;
      const format = (await world.admin.post(`${ownBase}/pdf-formats`, { name: 'f', design: { ...DESIGN, body: [{ type: 'text', text: 'ok' }] } }).expect(201)).body as { id: string };
      await world.admin.post(`${ownBase}/documents`, { formatId: format.id, moment: 'CREATION' }).expect(201);
      await world.db.platform.query(`UPDATE pdf_formats SET design = $1::jsonb WHERE tenant_id = $2 AND id = $3`, [JSON.stringify({ ...DESIGN, body: [{ type: 'text', text: '{{field.GONE}}' }] }), world.tenant.tenantId, format.id]);
      await expect(publishVersion(world.admin, own.workflowId, own.versionId, { steps: [{ key: 'start', type: 'START' }, { key: 'end', type: 'END' }], transitions: [{ from: 'start', to: 'end', type: 'DEFAULT' }] })).rejects.toThrow(/DOCUMENT_FIELD_UNKNOWN/);
    });
  });

  describe('failures and limits', () => {
    it('rejects a template that is not a real PDF or is encrypted, and one that is not the caller’s upload', async () => {
      const fake = Buffer.from('%PDF-1.4\nnot really a pdf\n%%EOF');
      const slot = (await world.admin.post('/pdf-templates/uploads', { files: [declare({ name: 'raro.pdf', content: fake })] }).expect(201)).body.uploads[0] as { fileId: string; url: string; method: string; headers: Record<string, string> };
      await putToStorage(slot, fake);
      await world.admin.post(`/pdf-templates/uploads/${slot.fileId}/confirm`).expect(200);
      const response = await world.admin.post(`${base()}/pdf-templates`, { fileId: slot.fileId, name: 'raro' }).expect(422);
      expect(response.body.error.code).toBe('PDF_TEMPLATE_INVALID');
      await requester.client.post(`${base()}/pdf-templates`, { fileId: slot.fileId, name: 'x' }).expect(403);
    });

    it('a format that names a field the workflow does not have cannot be saved', async () => {
      const response = await world.admin.post(`${base()}/pdf-formats`, { name: unique('Malo'), design: { ...DESIGN, body: [{ type: 'text', text: '{{field.NOPE}}' }] } }).expect(422);
      expect(response.body.error.code).toBe('PDF_DESIGN_INVALID');
      expect(JSON.stringify(response.body.error.details)).toContain('DOCUMENT_FIELD_UNKNOWN');
    });

    it('a format used by a workflow document cannot be deleted; deactivating it stops the documents', async () => {
      const format = await newFormat();
      const binding = await bindFormat(format.id, null);
      await world.admin.delete(`${base()}/pdf-formats/${format.id}`).expect(409);
      await world.admin.delete(`${base()}/documents/${binding.id}`).expect(204);
      await world.admin.delete(`${base()}/pdf-formats/${format.id}`).expect(204);
    });

    it('a document source switched off after the event was queued is skipped without failing', async () => {
      const format = await newFormat();
      const binding = await bindFormat(format.id, 'CREATION');
      const ticket = await create();
      await world.admin.patch(`${base()}/documents/${binding.id}`, { isActive: false }).expect(200);
      await worker.deliver();
      expect((await rows(ticket.id)).filter((row) => row.is_current)).toHaveLength(0);
      const failed = await db.platform.query(`SELECT 1 FROM outbox_events WHERE tenant_id = $1 AND type = 'document.generate' AND payload->>'ticketId' = $2 AND status <> 'DONE'`, [world.tenant.tenantId, ticket.id]);
      expect(failed.rowCount).toBe(0);
    });

    it('a document that cannot be drawn fails for good and leaves no rows and no usage', async () => {
      const format = await newFormat();
      const binding = await bindFormat(format.id, 'CREATION');
      await db.platform.query(`UPDATE pdf_formats SET design = '{"version": 1}'::jsonb WHERE tenant_id = $1 AND id = $2`, [world.tenant.tenantId, format.id]);
      const used = await usedBytes();
      const ticket = await create();
      await worker.deliver();
      expect(await rows(ticket.id)).toEqual([]);
      expect(await usedBytes()).toBe(used);
      const events = await db.platform.query<{ status: string }>(`SELECT status FROM outbox_events WHERE tenant_id = $1 AND type = 'document.generate' AND payload->>'ticketId' = $2`, [world.tenant.tenantId, ticket.id]);
      expect(events.rows.map((row) => row.status)).toContain('FAILED');
      await world.admin.patch(`${base()}/documents/${binding.id}`, { isActive: false }).expect(200);
    });

    it('generation is never refused for quota: it is stored and counted even when the plan is full', async () => {
      const plan = (await db.platform.query<{ id: string }>(`INSERT INTO plans (code, name, storage_base_bytes, storage_per_user_bytes, storage_grace_percent) VALUES ($1, 'Tiny', 1000, 0, 0) RETURNING id`, [unique('plan')])).rows[0]!.id;
      const own = await TicketWorld.create(db, app);
      await db.platform.query('UPDATE tenants SET plan_id = $1 WHERE id = $2', [plan, own.tenant.tenantId]);
      const asker = await own.member([grant('create'), grant('read_created')]);
      const ownFlow = await publishFlow(own.admin, { ...simpleFlow(), fields: [{ step: 'start', code: 'PROVIDER', type: 'TEXT', capture: 'CREATION' }] });
      const format = (await own.admin.post(`/workflows/${ownFlow.workflowId}/pdf-formats`, { name: 'f', design: { ...DESIGN, body: [{ type: 'text', text: 'hola' }] } }).expect(201)).body as { id: string };
      await own.admin.post(`/workflows/${ownFlow.workflowId}/documents`, { formatId: format.id, moment: 'CREATION' }).expect(201);
      const ticket = (await asker.client.post('/tickets', { subcategoryId: ownFlow.subcategoryId, title: 't', values: { PROVIDER: 'x' } }).expect(201)).body as { id: string };
      await worker.deliver();
      expect(await usedBytes(own.tenant.tenantId)).toBeGreaterThan(1000n);
      expect((await db.platform.query('SELECT 1 FROM ticket_documents WHERE tenant_id = $1 AND ticket_id = $2', [own.tenant.tenantId, ticket.id])).rowCount).toBe(1);
      await asker.client.post('/files/uploads', { files: [{ name: 'a.pdf', sizeBytes: 10, sha256: 'a'.repeat(64) }] }).expect(422);
    });
  });

  describe('permissions and tenant isolation', () => {
    it('needs the PdfDocument permissions, and the preview is read-only', async () => {
      await requester.client.get(`${base()}/pdf-formats`).expect(403);
      await requester.client.post(`${base()}/pdf-formats`, { name: 'x', design: DESIGN }).expect(403);
      await requester.client.get(`${base()}/documents`).expect(403);
      await requester.client.post('/pdf-templates/uploads', { files: [{ name: 'a.pdf', sizeBytes: 10, sha256: 'a'.repeat(64) }] }).expect(403);
    });

    it('another tenant sees none of it: ids of this tenant are 404 for them, and the worker draws nothing across tenants', async () => {
      const other = await TicketWorld.create(db, app);
      const otherBase = `/workflows/${flow.workflowId}`;
      const format = await newFormat();
      const binding = await bindFormat(format.id, null);
      await other.admin.get(`${otherBase}/pdf-formats`).expect(404);
      await other.admin.get(`${otherBase}/pdf-formats/${format.id}`).expect(404);
      await other.admin.post(`${otherBase}/pdf-formats/${format.id}/preview`, {}).expect(404);
      await other.admin.get(`${otherBase}/documents/${binding.id}`).expect(404);

      const ownFlow = await publishFlow(other.admin, { ...simpleFlow(), fields: [{ step: 'start', code: 'PROVIDER', type: 'TEXT', capture: 'CREATION' }] });
      const ownBase = `/workflows/${ownFlow.workflowId}`;
      await other.admin.get(`${ownBase}/pdf-formats/${format.id}`).expect(404);
      await other.admin.post(`${ownBase}/documents`, { formatId: format.id, moment: 'CREATION' }).expect(404);
      await other.admin.patch(`${ownBase}/documents/${binding.id}`, { isActive: false }).expect(404);

      const asker = await other.member([grant('create'), grant('read_created')]);
      const ticket = (await asker.client.post('/tickets', { subcategoryId: ownFlow.subcategoryId, title: 't', values: {} }).expect(201)).body as { id: string };
      await db.platform.query(`INSERT INTO outbox_events (tenant_id, type, payload) VALUES ($1, 'document.generate', $2::jsonb)`, [
        other.tenant.tenantId,
        JSON.stringify({ ticketId: ticket.id, ticketEventId: '0199a000-0000-7000-8000-000000000001', workflowDocumentId: binding.id, role: 'MAIN_DOCUMENT', stepId: null, trigger: 'CREATION' }),
      ]);
      await worker.deliver();
      expect((await db.platform.query('SELECT 1 FROM ticket_documents WHERE tenant_id = $1', [other.tenant.tenantId])).rowCount).toBe(0);
      const mine = await create();
      await worker.deliver();
      const [document] = await documentsOf(mine.id);
      await asker.client.get(`/tickets/${mine.id}/files/${document?.file.id ?? '0199a000-0000-7000-8000-000000000009'}/download-url`).expect(404);
    });
  });
});
