/** Every action the audit trail records: `<subject>.<verb>`. A closed list, so a typo cannot create a new kind of event. */
export const AUDIT_ACTIONS = [
  'member.invited',
  'member.invitation_resent',
  'member.updated',
  'member.deactivated',
  'member.reactivated',
  'role.created',
  'role.updated',
  'role.activated',
  'role.deactivated',
  'role.deleted',
  'role.permissions_replaced',
  'group.created',
  'group.updated',
  'group.activated',
  'group.deactivated',
  'group.members_replaced',
  'group.member_added',
  'group.member_removed',
  'approval_group.created',
  'approval_group.updated',
  'approval_group.activated',
  'approval_group.deactivated',
  'approval_group.approvers_replaced',
  'approval_group.members_replaced',
  'approval_group.member_added',
  'approval_group.member_removed',
  'approval_group_type.created',
  'approval_group_type.updated',
  'approval_group_type.deleted',
  'workflow.created',
  'workflow.updated',
  'workflow.version_published',
  'calculator.config_updated',
  'calculator.config_removed',
  'tenant.security_policy_updated',
  'account.password_changed',
  'account.mfa_enabled',
  'account.mfa_disabled',
  'account.mfa_backup_codes_regenerated',
  'file.download_url_issued',
  'pdf_template.download_url_issued',
  'report.exported',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
