/** Titles of the exported sheets and columns (what the end user reads). */
export const reportsEs = {
  filters: { sheet: 'Filtros', name: 'Filtro', value: 'Valor', from: 'Desde', to: 'Hasta', generatedAt: 'Generado (UTC)', user: 'Usuario', company: 'Empresa', workflow: 'Flujo', department: 'Departamento', site: 'Sede' },
  summary: { sheet: 'Resumen', metric: 'Indicador', value: 'Valor', created: 'Creados', closed: 'Cerrados', open: 'Abiertos', stepOnTimePct: '% a tiempo (paso total)', responsibleOnTimePct: '% a tiempo (responsable)', avgResolutionMin: 'Tiempo medio de resolución (min hábiles)', medianResolutionMin: 'Mediana de resolución (min hábiles)', unmeasuredTickets: 'Cerrados sin medir' },
  responsibles: { sheet: 'SLA por responsable', user: 'Responsable', pool: '(sin tomar)', clocks: 'Relojes', onTime: 'A tiempo', late: 'Atrasados', handedOff: 'Pasados a otro', noSla: 'Sin SLA', compliance: '% cumplimiento', avg: 'Promedio (min)', median: 'Mediana (min)', paused: 'Pausa media (min)' },
  steps: { sheet: 'SLA por paso', workflow: 'Flujo', step: 'Paso', visits: 'Visitas', onTime: 'A tiempo', late: 'Atrasadas', noSla: 'Sin SLA', compliance: '% cumplimiento', avg: 'Promedio (min)', median: 'Mediana (min)', p90: 'P90 (min)', paused: 'Pausa media (min)', reprocesses: 'Reprocesos' },
  ranking: { sheet: 'Ranking', unranked: 'Sin posición', rank: 'Puesto', user: 'Usuario', delivered: 'Tickets', onTime: 'A tiempo', late: 'Atrasados', errors: 'Errores', compliance: 'Cumplimiento', quality: 'Calidad', score: 'Puntaje', median: 'Mediana (min)' },
  distribution: { stepSheet: 'Tiempos por paso', workflowSheet: 'Tiempos por flujo', workflow: 'Flujo', step: 'Paso', count: 'Casos', min: 'Mín', p25: 'P25', median: 'Mediana', p75: 'P75', p90: 'P90', max: 'Máx' },
  incidents: { stepSheet: 'Novedades por paso', openerSheet: 'Novedades por quien las abre', assigneeSheet: 'Novedades por responsable', group: 'Grupo', count: 'Novedades', open: 'Abiertas', resolved: 'Resueltas', avgPaused: 'Pausa media (min)', medianPaused: 'Pausa mediana (min)' },
  categories: { sheet: 'Categorías', category: 'Categoría', subcategory: 'Subcategoría', total: '(total)', created: 'Creados', open: 'Abiertos', closed: 'Cerrados', avgResolution: 'Resolución media (min)' },
  backlog: { sheet: 'Pendientes', workflow: 'Flujo', step: 'Paso', open: 'Abiertos', paused: 'En pausa', overdue: 'Vencidos', avgAge: 'Antigüedad media (días)', maxAge: 'Antigüedad máxima (días)', avgInStep: 'Horas medias en el paso', upTo1: 'Hasta 1 día', upTo3: 'Hasta 3 días', upTo7: 'Hasta 7 días', over7: 'Más de 7 días' },
  user: { summarySheet: 'Usuario', clocksSheet: 'Relojes del usuario', ticket: 'Ticket', workflow: 'Flujo', step: 'Paso', loop: 'Vuelta', startedAt: 'Inicio (UTC)', completedAt: 'Fin (UTC)', dueAt: 'Vence (UTC)', business: 'Minutos hábiles', paused: 'Pausa (min)', result: 'Resultado', reason: 'Motivo del cierre', onTime: 'A tiempo', late: 'Atrasado' },
} as const;
